//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class fileupload
    {
        public int fid { get; set; }
        public int Reqid { get; set; }
        public string filepath { get; set; }
    
        public virtual MaintanenceTable MaintanenceTable { get; set; }
    }
}
