//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintanenceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintanenceTable()
        {
            this.fileuploads = new HashSet<fileupload>();
        }
    
        public int Reqid { get; set; }
        public System.DateTime reqdate { get; set; }
        public string request { get; set; }
        public int uid { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> RejApproveDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fileupload> fileuploads { get; set; }
        public virtual RegUser RegUser { get; set; }
        public virtual fileupload fileupload { get; set; }
    }
}
