//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSdbEntities : DbContext
    {
        public BMSdbEntities()
            : base("name=BMSdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fileupload> fileuploads { get; set; }
        public virtual DbSet<MaintanenceTable> MaintanenceTables { get; set; }
        public virtual DbSet<RegUser> RegUsers { get; set; }
    }
}
